### ISSUE TITLE
Team Fortress 2 | Invalid Signature

### ISSUE THREAD

**Issue by fxss-repository** [SilvDev/Command_Buffer#1]
L 07/17/2024 - 16:28:10: [SM] Exception reported: Failed to find "CCommandBuffer::InsertCommand" signature.
L 07/17/2024 - 16:28:10: [SM] Blaming: command_buffer.smx
L 07/17/2024 - 16:28:10: [SM] Call stack trace:
L 07/17/2024 - 16:28:10: [SM]   [0] SetFailState
L 07/17/2024 - 16:28:10: [SM]   [1] Line 134, /home/forums/content/files/8/5/7/7/8/170776.attach::OnPluginStart
L 07/17/2024 - 16:28:10: [SM] Unable to load plugin "command_buffer.smx": Error detected in plugin startup (see error logs)

**Comment by SilvDev** [comment]
Which game is this for?

**Comment by SilvDev** [comment]
2.9a (05-Aug-2024)
	- Fixed TF2 signature being broken on Windows due to some game udpate. Thanks to "LapplandBro" for reporting.
